version: "2.1"

services:
  api:
    image: ${API_IMAGE}
    env_file:
      - .env
    volumes:
      - ./updates:/app/updates
    ports:
      - "8080:8080"
    expose:
      - "8080"
    restart: unless-stopped
