version: "2.1"

services:
  api:
    image: ${API_IMAGE}
    env_file:
      - .env
    volumes:
      - ./updates:/app/updates
    ports:
      - "8080:8080"
    expose:
      - "8080"
    restart: unless-stopped

  caddy:
    profiles:
      - public
    image: caddy:2.10-alpine
    depends_on:
      - api
    env_file:
      - .env
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config:
